version: 0.0
os: linux
files:
    - source: .
    - destination: /home/ec2-user/bot
hooks:
    AfterInstall:
        - location: scripts/init
        timeout: 300
        runas: root
    ApplicationStart:
        - location: scripts/start
        timeout: 300
        runas: ec2-user

